# Generated by Django 4.2.6 on 2023-10-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='ex_time',
        ),
        migrations.CreateModel(
            name='C_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_time', models.DateTimeField()),
                ('sec_time', models.DateTimeField()),
                ('teacher', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.courses')),
            ],
        ),
    ]
